"""
Higher-level utility classes for browser automation with Trio CDP.

This module provides Puppeteer-inspired abstractions for common browser automation
tasks like keyboard input, mouse actions, and element interactions, while keeping
everything in pure CDP without JavaScript injection.
"""
from __future__ import annotations
import typing
from dataclasses import dataclass

import cdp
import trio
from cdp import dom, input_, page, runtime

if typing.TYPE_CHECKING:
    from .context import CdpSession


class Keyboard:
    """
    Keyboard provides an API for managing a virtual keyboard.
    
    The high-level methods like ``type`` and ``press`` ensure proper key event
    sequencing (keyDown, keyPress, keyUp) for realistic keyboard simulation.
    """
    
    def __init__(self, session: 'CdpSession'):
        """
        Initialize a Keyboard instance.
        
        :param session: CDP session to use for sending keyboard events
        """
        self._session = session
        self._pressed_keys = set()
    
    async def down(self, key: str, text: typing.Optional[str] = None) -> None:
        """
        Dispatch a keydown event.
        
        :param key: Name of the key to press (e.g., 'Enter', 'Tab', 'a')
        :param text: Text generated by the key press (if applicable)
        """
        self._pressed_keys.add(key)
        await self._session.execute(input_.dispatch_key_event(
            type_='keyDown',
            key=key,
            text=text
        ))
    
    async def up(self, key: str) -> None:
        """
        Dispatch a keyup event.
        
        :param key: Name of the key to release
        """
        self._pressed_keys.discard(key)
        await self._session.execute(input_.dispatch_key_event(
            type_='keyUp',
            key=key
        ))
    
    async def press(self, key: str, delay: float = 0) -> None:
        """
        Press a key, optionally with a delay between keydown and keyup.
        
        :param key: Name of the key to press (e.g., 'Enter', 'Tab', 'a')
        :param delay: Time to wait between keydown and keyup in seconds
        """
        await self.down(key, key if len(key) == 1 else None)
        if delay > 0:
            await trio.sleep(delay)
        await self.up(key)
    
    async def type(self, text: str, delay: float = 0) -> None:
        """
        Type a string of text character by character.
        
        :param text: Text to type
        :param delay: Time to wait between key presses in seconds
        """
        for char in text:
            await self.press(char, delay)
            if delay > 0:
                await trio.sleep(delay)


class Mouse:
    """
    Mouse provides an API for managing a virtual mouse.
    
    The high-level methods handle coordinate calculation and event sequencing
    for realistic mouse simulation.
    """
    
    def __init__(self, session: 'CdpSession'):
        """
        Initialize a Mouse instance.
        
        :param session: CDP session to use for sending mouse events
        """
        self._session = session
        self._x = 0
        self._y = 0
        self._button = 'none'
    
    async def move(self, x: float, y: float, steps: int = 1) -> None:
        """
        Move the mouse to a new position.
        
        :param x: X coordinate
        :param y: Y coordinate
        :param steps: Number of intermediate steps for the movement (smoother = more steps)
        """
        if steps <= 0:
            steps = 1
        
        from_x, from_y = self._x, self._y
        
        for i in range(1, steps + 1):
            self._x = from_x + (x - from_x) * (i / steps)
            self._y = from_y + (y - from_y) * (i / steps)
            
            await self._session.execute(input_.dispatch_mouse_event(
                type_='mouseMoved',
                x=self._x,
                y=self._y
            ))
    
    async def click(
        self,
        x: float,
        y: float,
        button: str = 'left',
        click_count: int = 1,
        delay: float = 0
    ) -> None:
        """
        Click at a specific position.
        
        :param x: X coordinate
        :param y: Y coordinate
        :param button: Mouse button ('left', 'right', 'middle')
        :param click_count: Number of clicks (1 for single, 2 for double)
        :param delay: Time to wait between mousedown and mouseup in seconds
        """
        await self.move(x, y)
        await self.down(button, click_count)
        if delay > 0:
            import trio
            await trio.sleep(delay)
        await self.up(button, click_count)
    
    async def down(self, button: str = 'left', click_count: int = 1) -> None:
        """
        Dispatch a mousedown event.
        
        :param button: Mouse button ('left', 'right', 'middle')
        :param click_count: Number of clicks
        """
        self._button = button
        await self._session.execute(input_.dispatch_mouse_event(
            type_='mousePressed',
            x=self._x,
            y=self._y,
            button=button,
            click_count=click_count
        ))
    
    async def up(self, button: str = 'left', click_count: int = 1) -> None:
        """
        Dispatch a mouseup event.
        
        :param button: Mouse button ('left', 'right', 'middle')
        :param click_count: Number of clicks
        """
        self._button = 'none'
        await self._session.execute(input_.dispatch_mouse_event(
            type_='mouseReleased',
            x=self._x,
            y=self._y,
            button=button,
            click_count=click_count
        ))


@dataclass
class ElementHandle:
    """
    Represents a handle to a DOM element.
    
    Provides methods for interacting with elements in a convenient way.
    """
    
    session: 'CdpSession'
    node_id: dom.NodeId
    
    async def click(self, button: str = 'left', click_count: int = 1, delay: float = 0) -> None:
        """
        Click on the element.
        
        :param button: Mouse button ('left', 'right', 'middle')
        :param click_count: Number of clicks
        :param delay: Time to wait between mousedown and mouseup in seconds
        """
        # Get the element's bounding box
        box_model = await self.session.execute(dom.get_box_model(self.node_id))
        
        # Calculate center point from content quad
        content = box_model.content
        x = (content[0] + content[2] + content[4] + content[6]) / 4
        y = (content[1] + content[3] + content[5] + content[7]) / 4
        
        # Use the mouse utility to click
        mouse = Mouse(self.session)
        await mouse.click(x, y, button, click_count, delay)
    
    async def type(self, text: str, delay: float = 0) -> None:
        """
        Type text into the element (focuses the element first).
        
        :param text: Text to type
        :param delay: Time to wait between key presses in seconds
        """
        # Focus the element first
        await self.session.execute(dom.focus(self.node_id))
        
        # Type the text
        keyboard = Keyboard(self.session)
        await keyboard.type(text, delay)
    
    async def get_attribute(self, name: str) -> typing.Optional[str]:
        """
        Get an attribute value from the element.
        
        :param name: Attribute name
        :return: Attribute value or None if not found
        """
        attributes = await self.session.execute(dom.get_attributes(self.node_id))
        
        # Attributes are returned as a flat list [name1, value1, name2, value2, ...]
        for i in range(0, len(attributes), 2):
            if attributes[i] == name:
                return attributes[i + 1]
        return None
    
    async def get_property(self, name: str) -> typing.Any:
        """
        Get a JavaScript property value from the element.
        
        :param name: Property name
        :return: Property value
        """
        # Get the remote object for this node
        remote_object = await self.session.execute(
            dom.resolve_node(self.node_id)
        )
        
        # Get the property
        result = await self.session.execute(
            runtime.call_function_on(
                function_declaration=f'function() {{ return this.{name}; }}',
                object_id=remote_object.object_id,
                return_by_value=True
            )
        )
        
        return result.result.value if result.result else None
    
    async def get_outer_html(self) -> str:
        """
        Get the outer HTML of the element.
        
        :return: Outer HTML string
        """
        outer_html = await self.session.execute(dom.get_outer_html(self.node_id))
        return outer_html


async def query_selector(
    session: 'CdpSession',
    selector: str,
    node_id: typing.Optional[dom.NodeId] = None
) -> typing.Optional[ElementHandle]:
    """
    Find an element matching a CSS selector.
    
    :param session: CDP session
    :param selector: CSS selector
    :param node_id: Parent node to search within (searches from document root if None)
    :return: ElementHandle for the first matching element, or None if not found
    """
    if node_id is None:
        # Get the document root
        document = await session.execute(dom.get_document())
        node_id = document.node_id
    
    result_node_id = await session.execute(dom.query_selector(node_id, selector))
    
    if result_node_id == 0:
        return None
    
    return ElementHandle(session=session, node_id=result_node_id)


async def query_selector_all(
    session: 'CdpSession',
    selector: str,
    node_id: typing.Optional[dom.NodeId] = None
) -> typing.List[ElementHandle]:
    """
    Find all elements matching a CSS selector.
    
    :param session: CDP session
    :param selector: CSS selector
    :param node_id: Parent node to search within (searches from document root if None)
    :return: List of ElementHandle objects for matching elements
    """
    if node_id is None:
        # Get the document root
        document = await session.execute(dom.get_document())
        node_id = document.node_id
    
    result_node_ids = await session.execute(
        dom.query_selector_all(node_id, selector)
    )
    
    return [
        ElementHandle(session=session, node_id=nid)
        for nid in result_node_ids
    ]


async def wait_for_selector(
    session: 'CdpSession',
    selector: str,
    timeout: float = 30,
    visible: bool = False
) -> typing.Optional[ElementHandle]:
    """
    Wait for an element matching a CSS selector to appear.
    
    :param session: CDP session
    :param selector: CSS selector
    :param timeout: Maximum time to wait in seconds
    :param visible: If True, wait for element to be visible (not just present in DOM)
    :return: ElementHandle for the matching element, or None if timeout
    """
    import trio
    
    async def check_element():
        element = await query_selector(session, selector)
        if element is None:
            return None
        
        if visible:
            # Check if element is visible by getting its box model
            try:
                await session.execute(dom.get_box_model(element.node_id))
                return element
            except Exception:
                # If get_box_model fails, element is not visible
                return None
        
        return element
    
    # Try immediately first
    element = await check_element()
    if element is not None:
        return element
    
    # Poll with backoff
    start_time = trio.current_time()
    delay = 0.1
    max_delay = 1.0
    
    while trio.current_time() - start_time < timeout:
        await trio.sleep(delay)
        element = await check_element()
        if element is not None:
            return element
        
        # Exponential backoff
        delay = min(delay * 1.5, max_delay)
    
    return None
